Repository RedHatInsights/topological_inventory-core, pull requests merged in 2020-10, with the labels that each got.

#210 Finishing tasks with archived service_instance
  lib/topological_inventory/schema/default.rb
Labels: hacktoberfest-accepted

#208 Changelog 1.1.8
  CHANGELOG.md
  lib/topological_inventory/core/version.rb
Labels: changelog, hacktoberfest-accepted

#209 bump miq messaging version
  CHANGELOG.md
  lib/topological_inventory/core/version.rb
  topological_inventory-core.gemspec
Labels: unmergeable
